- name: Deploy Engaging Website
  hosts: my_vms
  become: yes
  vars:
    prize_message: "just click the button below for a free iphone 16"
  tasks:
    - name: Install git, apache2, and net-tools
      apt:
        name:
          - git
          - apache2
          - net-tools
        state: present
        update_cache: true

    - name: Copy index.html file with variable
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes
